appBandas/urls.py
from django.urls import path
from . import views

app_name = 'appBandas'

urlpatterns = [
    path('', views.listaBandas_view, name='bandas'),
    path('bandas/<int:banda_id>/', views.banda_view, name='bandaAlbuns'),
    path('albuns/<int:album_id>/', views.album_view, name='albumMusicas'),
    path('musicas/<int:musica_id>/', views.musica_view, name='musicas'),
    path('banda/novo', views.novo_banda_view, name="novo_banda"),
    path('banda/<int:banda_id>/edita', views.edita_banda_view, name="edita_banda"),
    path('banda/<int:banda_id>/apaga', views.apaga_banda_view, name="apaga_banda"),
    path('album/novo/', views.novo_album_view, name="novo_album"),
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('projeto/<int:id>/', views.projeto_detalhes_view, name='projeto_detalhes'),
    path('novo/', views.novo_projeto_view, name='novo_projeto'),
    path('projeto/<int:id>/editar/', views.editar_projeto_view, name='editar_projeto'),
    path('projeto/<int:id>/apagar/', views.apagar_projeto_view, name='apagar_projeto'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),  # Adiciona a URL de logout
]

project/urls.py
from django.contrib import admin
from django.urls import path, include   # incluir include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),  # novo path
    path('pwsite/', include('pwsite.urls')),
    path('novaapp/', include('novaapp.urls')),
    path('appBandas/', include('appBandas.urls')),
    path('artigos/', include('artigos.urls')),
    path('appFestivais/', include('appFestivais.urls')),
    path('appCursos/', include('appCursos.urls')),
    path('portfolio/', include('portfolio.urls')),
]

pwsite/urls.py
# pwsite/urls.py

from django.urls import path
from . import views  # importamos views para poder usar as suas funções

app_name = 'pwsite'

urlpatterns = [
    path('index/', views.index_view, name='index'),
    path('sobre/', views.sobre_view, name='sobre'),
    path('interesses/', views.interesses_view, name='interesses'),
]

portfolio/models.py
from django.db import models

class Perfil(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField()
    email = models.EmailField()
    profile_picture = models.ImageField(upload_to='media/', blank=True, null=True)

    def __str__(self):
        return self.name

class Projeto(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='media/', blank=True, null=True)
    url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

portfolio/forms.py
from django import forms
from .models import Projeto

class ProjetoForm(forms.ModelForm):
    class Meta:
        model = Projeto
        fields = ['title', 'description', 'image', 'url']

portfolio/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Perfil, Projeto
from .forms import ProjetoForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout


def home_view(request):
    profile = Perfil.objects.first()
    projetos = Projeto.objects.all()
    context = {
        'profile': profile,
        'projetos': projetos
    }
    return render(request, 'portfolio/home.html', context)

def projeto_detalhes_view(request, id):
    projeto = get_object_or_404(Projeto, id=id)
    context = {
        'projeto': projeto
    }
    return render(request, 'portfolio/projeto_detalhes.html', context)

@login_required
def novo_projeto_view(request):
    if request.method == 'POST':
        form = ProjetoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('portfolio:home')
    else:
        form = ProjetoForm()
    return render(request, 'portfolio/novo_projeto.html', {'form': form})

@login_required
def editar_projeto_view(request, id):
    projeto = get_object_or_404(Projeto, id=id)
    if request.method == 'POST':
        form = ProjetoForm(request.POST, request.FILES, instance=projeto)
        if form.is_valid():
            form.save()
            return redirect('portfolio:projeto_detalhes', id=projeto.id)
    else:
        form = ProjetoForm(instance=projeto)
    return render(request, 'portfolio/editar_projeto.html', {'form': form, 'projeto': projeto})

@login_required
def apagar_projeto_view(request, id):
    projeto = get_object_or_404(Projeto, id=id)
    if request.method == 'POST':
        projeto.delete()
        return redirect('portfolio:home')
    return render(request, 'portfolio/apagar_projeto.html', {'projeto': projeto})
    
def login_view(request):
    if request.method == "POST":
        user = authenticate(
            request,
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user:
            login(request, user)
            return redirect('portfolio:home')  # Redireciona para a página inicial após login bem-sucedido
        else:
            return render(request, 'portfolio/login.html', {
                'mensagem': 'Credenciais inválidas'
            })
        
    return render(request, 'portfolio/login.html')


def logout_view(request):
    logout(request)
    return redirect('portfolio:home')  # Redireciona para a página inicial após logout

portfolio/templates/portfolio/apagar_projeto.html
{% extends 'portfolio/layout.html' %}

{% block title %}Apagar Projeto - Meu Portfólio{% endblock %}

{% block content %}
    <h2>Apagar Projeto</h2>
    <p>Tem certeza que deseja apagar o projeto "{{ projeto.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar</button>
        <a href="{% url 'portfolio:projeto_detalhes' projeto.id %}">Cancelar</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/editar_projeto.html
{% extends 'portfolio/layout.html' %}

{% block title %}Editar Projeto - Meu Portfólio{% endblock %}

{% block content %}
    <h2>Editar Projeto</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/layout.html' %}

{% block title %}Home - Meu Portfólio{% endblock %}

{% block content %}
    <div class="profile-container">
        <div class="profile-image">
            {% if profile.profile_picture %}
                <img src="{{ profile.profile_picture.url }}" alt="{{ profile.name }}" class="rounded-image">
            {% endif %}
        </div>
        <div class="profile-info">
            <h1>{{ profile.name }}</h1>
            <p>{{ profile.bio }}</p>
        </div>
    </div>

    <h2>Projetos</h2>
    <ul>
        {% for projeto in projetos %}
            <li>
                <a href="{% url 'portfolio:projeto_detalhes' projeto.id %}">{{ projeto.title }}</a>
            </li>
        {% endfor %}
    </ul>

    {% if user.is_authenticated %}
        <a href="{% url 'portfolio:novo_projeto' %}"><button>Adicionar Novo Projeto</button></a>
    {% endif %}
{% endblock %}

portfolio/templates/portfolio/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Meu Portfólio{% endblock %}</title>
    <style>
        .errorlist {
            display: none;
        }
        body {
            background-color: white; /* Cor de fundo cinza */
            color: black; /* Cor do texto */
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            margin: 20;
        }
        header {
            background-color: #8ed1fc; /* Cor cinzento */
            color: white; /* Letras brancas */
            text-align: center; /* Texto centralizado */
            padding: 20px 0; /* Espaçamento interno */
            width: 100%;
        }
        a {
            color: #1DB954; /* Cor do texto das hiperligações */
            text-decoration: none; /* Remover sublinhado padrão */
        }
        .container {
            max-width: 800px;
            margin: 20 auto;
            padding: 20px;
        }
        .profile-container {
            display: flex;
            align-items: center;
            justify-content: flex-start; /* Alinhar itens à esquerda */
            margin-bottom: 20px;
        }
        .profile-image {
            margin-right: 20px;
        }
        .profile-info {
            max-width: 600px;
        }
        .rounded-image {
            border-radius: 30%; /* Torna a imagem redonda */
            max-width: 150px; /* Define um tamanho máximo para a imagem */
        }
        footer {
            text-align: center;
            padding: 20px 0;
            background-color: #8ed1fc;
            color: white;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
        .auth-buttons {
            margin-top: 10px;
        }
        .auth-buttons a, .auth-buttons form {
            display: inline-block;
            margin: 0 5px;
        }
        .auth-buttons button, .auth-buttons a {
            background-color: grey;
            color: black;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
            text-decoration: none;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <header>
        <h1>Meu Portfólio</h1>

        <a href="{% url 'portfolio:home' %}"><button>Home</button></a>
         {% if user.is_authenticated %}
            <a href="{% url 'portfolio:novo_projeto' %}"><button>Novo Projeto</button></a>
            <p>Username: {{ user.username }}</p>
            <form method="post" action="{% url 'portfolio:logout' %}" class="auth-buttons">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
        {% else %}
            <a href="{% url 'portfolio:login' %}"><button>Login</button></a>
        {% endif %}
    </header>

    <main>
        {% block content %}
            <!-- Este bloco será substituído pelo conteúdo específico de cada página -->
        {% endblock %}
    </main>

    <footer>
        <!-- Rodapé comum a todas as páginas -->
        <p>&copy; 2024 Meu Portfólio</p>
    </footer>
</body>
</html>

portfolio/templates/portfolio/login.html
{% extends 'portfolio/layout.html' %}

{% block content %}
    <h3>Login</h3>

    {% if mensagem %}
      <p>mensagem: {{ mensagem }}</p>
    {% endif %}
    <form action="{% url 'portfolio:login' %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="Username.." required>
      <input type="password" name="password" placeholder="Password.." required>
      <input type="submit" value="Entrar">
    </form>

{% endblock %}

portfolio/templates/portfolio/novo_projeto.html
{% extends 'portfolio/layout.html' %}

{% block title %}Adicionar Novo Projeto - Meu Portfólio{% endblock %}

{% block content %}
    <h2>Adicionar Novo Projeto</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/projeto_detalhes.html
{% extends 'portfolio/layout.html' %}

{% block title %}{{ projeto.title }} - Meu Portfólio{% endblock %}

{% block content %}
    <h1>{{ projeto.title }}</h1>
    {% if projeto.image %}
        <img src="{{ projeto.image.url }}" alt="{{ projeto.title }}" style="max-width: 400px;">
    {% endif %}
    <p>{{ projeto.description }}</p>
    {% if projeto.url %}
        <a href="{{ projeto.url }}">Link para o Projeto</a>
    {% endif %}

    {% if user.is_authenticated %}
        <a href="{% url 'portfolio:editar_projeto' projeto.id %}"><button>Editar Projeto</button></a>
        <a href="{% url 'portfolio:apagar_projeto' projeto.id %}"><button>Apagar Projeto</button></a>
    {% endif %}
{% endblock %}

portfolio/templates/portfolio/registo.html
{% extends 'portfolio/layout.html' %}

{% block content %}
    <h3>Registo</h3>

    <form action="{% url 'appBandas:registo' %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="O seu username.." required>
      <input type="text" name="nome" placeholder="O seu nome.." required>
      <input type="text" name="apelido" placeholder="O seu apelido.." required>
      <input type="email" name="email" placeholder="O seu email.." required>
      <input type="password" name="password" placeholder="Defina a sua password.." required>
      <input type="submit" value="Criar">
    </form>

    <a href="{% url 'appBandas:login' %}">Cancelar</a>

{% endblock %}