artigos/urls.py
from django.urls import path
from . import views

app_name = 'artigos'

urlpatterns = [
    path('', views.lista_autores, name='lista_autores'),
    path('artigos/<int:artigo_id>/', views.detalhe_artigo, name='detalhe_artigo'),
    path('autores/<int:autor_id>/artigos/', views.lista_artigos, name='lista_artigos'),
    path('artigos/<int:artigo_id>/comentarios/', views.comentarios_classificacoes, name='comentarios_classificacoes'),
    path('autor/novo/', views.novo_autor_view, name='novo_autor'),
    path('autor/<int:autor_id>/editar/', views.editar_autor_view, name='editar_autor'),
    path('autor/<int:autor_id>/apagar/', views.apagar_autor_view, name='apagar_autor'),
    path('artigo/novo/', views.novo_artigo_view, name='novo_artigo'),
    path('artigo/<int:artigo_id>/editar/', views.editar_artigo_view, name='editar_artigo'),
    path('artigo/<int:artigo_id>/apagar/', views.apagar_artigo_view, name='apagar_artigo'),
    path('comentario/novo/', views.novo_comentario_view, name='novo_comentario'),
    path('comentario/<int:comentario_id>/editar/', views.editar_comentario_view, name='editar_comentario'),
    path('comentario/<int:comentario_id>/apagar/', views.apagar_comentario_view, name='apagar_comentario'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include   # incluir include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),  # novo path
    path('pwsite/', include('pwsite.urls')),
    path('novaapp/', include('novaapp.urls')),
    path('appBandas/', include('appBandas.urls')),
    path('artigos/', include('artigos.urls')),
    path('appFestivais/', include('appFestivais.urls')),
    path('appCursos/', include('appCursos.urls')),
    path('portfolio/', include('portfolio.urls')),
]

pwsite/urls.py
# pwsite/urls.py

from django.urls import path
from . import views  # importamos views para poder usar as suas funções

app_name = 'pwsite'

urlpatterns = [
    path('index/', views.index_view, name='index'),
    path('sobre/', views.sobre_view, name='sobre'),
    path('interesses/', views.interesses_view, name='interesses'),
]

artigos/models.py
from django.db import models
import datetime



class Autor(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.nome}'

class Artigo(models.Model):
    title = models.CharField(max_length=100)
    post = models.TextField()
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE, null=True)
    data = models.DateField(default=datetime.date.today)

    def __str__(self):
        return f'{self.title}'


class Comentario(models.Model):
    autor = models.CharField(max_length=100)
    texto = models.TextField()

    MUITO_MAU = '1'
    MAU = '2'
    INDIFERENTE = '3'
    BOM = '4'
    MUITO_BOM = '5'

    RATINGS_CHOICES = [
        (MUITO_MAU, '1'),
        (MAU, '2'),
        (INDIFERENTE, '3'),
        (BOM, '4'),
        (MUITO_BOM, '5'),
    ]

    rating = models.CharField(max_length=10, choices=RATINGS_CHOICES, default=MUITO_MAU, blank=True, null=True)
    post = models.ForeignKey(Artigo, on_delete=models.CASCADE, related_name='comentarios')

    def str(self):
        return self.autor

artigos/forms.py
from django import forms
from .models import Autor, Artigo, Comentario

class AutorForm(forms.ModelForm):
    class Meta:
        model = Autor
        fields = '__all__'
        
        widgets = {
            'nome': forms.TextInput(attrs={
                'placeholder': 'Nome do Autor',
            }),
        }

class ArtigoForm(forms.ModelForm):
    class Meta:
        model = Artigo
        fields = '__all__'
        
        labels = {
            'title': 'Título',
            'post': 'Conteúdo',
            'autor': 'Autor',
            'data': 'Data de Publicação',
        }
        
        help_texts = {
            'data': 'Verifique a data de publicação',
        }

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = '__all__'
        
        labels = {
            'autor': 'Nome',
            'texto': 'Comentário',
            'rating': 'Avaliação',
            'post': 'Artigo',
        }
        
        help_texts = {
            'rating': 'Escolha uma classificação',
        }

        widgets = {
            'autor': forms.TextInput(attrs={
                'placeholder': 'Seu Nome',
            }),
            'texto': forms.Textarea(attrs={
                'placeholder': 'Seu Comentário',
            }),
        }

artigos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Autor, Artigo, Comentario
from .forms import AutorForm, ArtigoForm, ComentarioForm

def lista_autores(request):
    autores = Autor.objects.all()
    return render(request, 'artigos/lista_autores.html', {'autores': autores})

def lista_artigos(request, autor_id):
    autor = Autor.objects.get(id=autor_id)
    artigos = Artigo.objects.filter(autor=autor)
    return render(request, 'artigos/lista_artigos.html', {'autor': autor, 'artigos': artigos})

def comentarios_classificacoes(request, artigo_id):
    artigo = Artigo.objects.get(id=artigo_id)
    comentarios = Comentario.objects.filter(post=artigo)
    return render(request, 'artigos/comentarios_classificacoes.html', {'artigo': artigo, 'comentarios': comentarios})

def detalhe_artigo(request, artigo_id):
    artigo = Artigo.objects.get(id=artigo_id)
    return render(request, 'artigos/detalhe_artigo.html', {'artigo': artigo})

@login_required
def novo_autor_view(request):
    form = AutorForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('artigos:lista_autores')

    return render(request, 'artigos/novo_autor.html', {'form': form})

@login_required
def editar_autor_view(request, autor_id):
    autor = Autor.objects.get(id=autor_id)
    form = AutorForm(request.POST or None, instance=autor)
    if form.is_valid():
        form.save()
        return redirect('artigos:lista_autores')

    return render(request, 'artigos/editar_autor.html', {'form': form})

@login_required
def apagar_autor_view(request, autor_id):
    autor = Autor.objects.get(id=autor_id)
    autor.delete()
    return redirect('artigos:lista_autores')

@login_required
def novo_artigo_view(request):
    form = ArtigoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('artigos:lista_autores')

    return render(request, 'artigos/novo_artigo.html', {'form': form})

@login_required
def editar_artigo_view(request, artigo_id):
    artigo = Artigo.objects.get(id=artigo_id)
    form = ArtigoForm(request.POST or None, instance=artigo)
    if form.is_valid():
        form.save()
        return redirect('artigos:lista_artigos', autor_id=artigo.autor.id)  # Certifique-se de que autor_id é passado corretamente

    return render(request, 'artigos/editar_artigo.html', {'form': form, 'artigo': artigo})

@login_required
def apagar_artigo_view(request, artigo_id):
    artigo = Artigo.objects.get(id=artigo_id)
    artigo.delete()
    return redirect('artigos:lista_autores')

@login_required
def novo_comentario_view(request):
    form = ComentarioForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('artigos:lista_autores')

    return render(request, 'artigos/novo_comentario.html', {'form': form})

@login_required
def editar_comentario_view(request, comentario_id):
    comentario = Comentario.objects.get(id=comentario_id)
    form = ComentarioForm(request.POST or None, instance=comentario)
    if form.is_valid():
        form.save()
        return redirect('artigos:lista_autores')

    return render(request, 'artigos/editar_comentario.html', {'form': form})

@login_required
def apagar_comentario_view(request, comentario_id):
    comentario = Comentario.objects.get(id=comentario_id)
    artigo_id = comentario.post.id
    comentario.delete()
    return redirect('artigos:comentarios_classificacoes', artigo_id=artigo_id)

def login_view(request):
    if request.method == "POST":
        user = authenticate(
            request,
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user:
            login(request, user)
            return redirect(reverse('artigos:lista_autores'))
        else:
            return render(request, 'artigos/login.html', {
                'mensagem': 'Credenciais inválidas'
            })

    return render(request, 'artigos/login.html')

def logout_view(request):
    logout(request)
    return redirect('artigos:lista_autores')

artigos/templates/artigos/comentarios_classificacoes.html
{% extends "artigos/layout.html" %}

{% block title %}
    Comentários e Classificações de {{ artigo.title }}
{% endblock %}

{% block content %}
    <h2>Comentários e Classificações de {{ artigo.title }}</h2>
    <ul>
    {% for comentario in comentarios %}
        <li>
            {{ comentario.autor }} - {{ comentario.texto }} - {{ comentario.rating }}
            {% if request.user.is_authenticated %}
                <a href="{% url 'artigos:apagar_comentario' comentario.id %}" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja apagar este comentario?');"><button>Remover</button></a>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

artigos/templates/artigos/detalhe_artigo.html
{% extends "artigos/layout.html" %}

{% block title %}
    Detalhes do Artigo: {{ artigo.title }}
{% endblock %}

{% block content %}
    <h2>{{ artigo.title }}</h2>
    <p><strong>Autor:</strong> {{ artigo.autor.nome }}</p>
    <p><strong>Conteúdo:</strong></p>
    <p>{{ artigo.post }}</p>
    <p><a href="{% url 'artigos:comentarios_classificacoes' artigo.id %}">Ver Comentários</a></p>
{% endblock %}

artigos/templates/artigos/editar_artigo.html
{% extends 'artigos/layout.html' %}

{% block content %}
<h3>Editar Artigo</h3>
<form action="{% url 'artigos:editar_artigo' artigo.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Salvar">
</form>
{% endblock %}

artigos/templates/artigos/editar_autor.html
{% extends 'artigos/layout.html' %}

{% block content %}
<h3>Editar Autor</h3>
<form action="{% url 'artigos:editar_autor' autor.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Salvar">
</form>
{% endblock %}

artigos/templates/artigos/editar_comentario.html
{% extends 'artigos/layout.html' %}

{% block content %}
<h3>Editar Comentário</h3>
<form action="{% url 'artigos:editar_comentario' comentario.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Salvar">
</form>
{% endblock %}

artigos/templates/artigos/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Título Padrão{% endblock %}</title>
    <style>
        body {
            background-color: #181818; /* Cor de fundo cinza */
            color: white; /* Cor do texto */
        }
        header {
            background-color: #262626; /* Cor do cabeçalho */
            color: #fd0202; /* Cor do texto do cabeçalho */
            text-align: center; /* Texto centralizado */
            padding: 20px 0; /* Espaçamento interno */
        }
        a {
            color: #4385df; /* Cor do texto das hiperligações */
            text-decoration: none; /* Remover sublinhado padrão */
        }
        nav {
            background-color: #262626; /* Cor de fundo do nav */
            padding: 10px 0; /* Espaçamento interno */
        }
        nav ul {
            list-style-type: none; /* Remover marcadores da lista */
            padding: 0; /* Remover padding */
            text-align: center; /* Centralizar texto */
        }
        nav ul li {
            display: inline; /* Exibir itens em linha */
            margin: 0 10px; /* Margem entre itens */
        }
        nav ul li a {
            color: #4385df; /* Cor dos links */
        }
        footer {
            background-color: #262626; /* Cor do fundo do rodapé */
            color: white; /* Cor do texto do rodapé */
            text-align: center; /* Texto centralizado */
            padding: 10px 0; /* Espaçamento interno */
            position: absolute;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <header>
        <h1>Artigos</h1>

<a href="{% url 'artigos:lista_autores' %}"><button>Autores</button></a>
{% if request.user.is_authenticated %}
    <a href="{% url 'artigos:novo_autor' %}"><button>Novo Autor</button></a>
    <p>Username: {{ request.user.username }}</p>
    <a href="{% url 'artigos:logout' %}"><button>Logout</button></a>
{% else %}
    <a href="{% url 'artigos:login' %}"><button>Login</button></a>
{% endif %}

    </header>



    <main>
        {% block content %}
            <!-- Este bloco será substituído pelo conteúdo específico de cada página -->
        {% endblock %}
    </main>

    <footer>
        <!-- Rodapé comum a todas as páginas -->
        <p>&copy; 2024 Meu Site de Artigos</p>
    </footer>
</body>
</html>

artigos/templates/artigos/lista_artigos.html
{% extends "artigos/layout.html" %}

{% block title %}
    Lista de Artigos de {{ autor.nome }}
{% endblock %}

{% block content %}
    <h2>Artigos de {{ autor.nome }}</h2>
    <ul>
    {% for artigo in artigos %}
        <li>
            <a href="{% url 'artigos:detalhe_artigo' artigo.id %}">{{ artigo.title }}</a> -
            <a href="{% url 'artigos:comentarios_classificacoes' artigo.id %}">Ver Comentários</a>
        </li>
        {% if request.user.is_authenticated %}
                <a href="{% url 'artigos:editar_artigo' artigo.id %}"><button>Editar</button></a>
                <a href="{% url 'artigos:apagar_artigo' artigo.id %}" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja apagar este artigo?');"><button>Remover</button></a>
            {% endif %}
    {% endfor %}
    </ul>
{% endblock %}

artigos/templates/artigos/lista_autores.html
{% extends "artigos/layout.html" %}

{% block title %}
    Lista de Autores
{% endblock %}

{% block content %}
    <h2>Lista de Autores</h2>
    {% if request.user.is_authenticated %}
        <a href="{% url 'artigos:novo_autor' %}">
            <button>Criar Novo Autor</button>
    {% endif %}
    <ul>
    {% for autor in autores %}
        <li>{{ autor.nome }} - <a href="{% url 'artigos:lista_artigos' autor.id %}">Ver Artigos</a></li>
    {% endfor %}
    </ul>
{% endblock %}

artigos/templates/artigos/login.html
{% extends 'artigos/layout.html' %}

{% block content %}
<h3>Login</h3>

{% if mensagem %}
  <p>{{ mensagem }}</p>
{% endif %}
<form action="{% url 'artigos:login' %}" method="post">
  {% csrf_token %}
  <input type="text" name="username" placeholder="Username.." required>
  <input type="password" name="password" placeholder="Password.." required>
  <input type="submit" value="Entrar">
</form>
{% endblock %}

artigos/templates/artigos/novo_artigo.html
{% extends 'artigos/layout.html' %}

{% block content %}
<h3>Novo Artigo</h3>
<form action="{% url 'artigos:novo_artigo' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Criar">
</form>
{% endblock %}

artigos/templates/artigos/novo_autor.html
{% extends 'artigos/layout.html' %}

{% block content %}
<h3>Novo Autor</h3>
<form action="{% url 'artigos:novo_autor' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Criar">
</form>
{% endblock %}

artigos/templates/artigos/novo_comentario.html
{% extends 'artigos/layout.html' %}

{% block content %}
<h3>Novo Comentário</h3>
<form action="{% url 'artigos:novo_comentario' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Enviar">
</form>
{% endblock %}

artigos/templates/artigos/registo.html
{% extends 'artigos/layout.html' %}

{% block content %}
    <h3>Registo</h3>
    
    <form action="{% url 'registo' %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="O seu username..">
      <input type="text" name="nome" placeholder="O seu nome..">
      <input type="text" name="apelido" placeholder="O seu apelido..">
      <input type="email" name="email" placeholder="O seu email..">
      <input type="password" name="password" placeholder="Defina a sua password..">
      <input type="submit" value="Criar">
    </form> 
    
    <a href="{% url 'login' %}">Cancelar</a>

{% endblock %}